#! /bin/bash

export TACHYON_ROOT=${HOME}/tachyon
export GOPATH=${TACHYON_ROOT}:/home/mick/go

go run ./signal_to_image.go ./signal ./image.whd

go run ../whd2tif/whd2tif.go  ./image.whd ./image.tif

