#! /bin/bash

export TACHYON_ROOT=${HOME}/tachyon
export GOPATH=${TACHYON_ROOT}

# These two instances can be started in any order.

# This one accepts the connection.
go run ./tachyon_example_01.go & 

# This one initiates the connection.
go run ./tachyon_example_01.go -initiate &

